package com.nt.constinjec;

import org.springframework.beans.factory.BeanFactory;
import org.springframework.beans.factory.xml.XmlBeanFactory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;

import com.nt.bean.WishMessage;

public class ConstructorInjection 
{
	static {
		System.out.println("main method()");
	}
    public static void main( String[] args )
    {
    	Resource res=null;
    	BeanFactory bf=null;
    	WishMessage wm=null;
    	String result=null;
    	
    	// locate the file 
       // res=new FileSystemResource("src/main/java/com/nt/cnfgs/applicationContext.xml");	// This is Relative path (Recommanded)
    	// This is absolute path
    	//  res=new FileSystemResource("E:\\SPRING NTSP713\\03IOC_ConstructorInjection\\src\\main\\java\\com\\nt\\cnfgs\\applicationContext.xml");
        
    	// This is recommanded and company is use this only
    	res=new ClassPathResource("com/nt/cnfgs/applicationContext.xml");	// This is absolute path 
    	
    	// creating a container
        bf=new XmlBeanFactory(res);
        // get bean id and typecast
     //   wm=(WishMessage)bf.getBean("wmg");	// not use in company
        wm=bf.getBean("wmg",WishMessage.class);	// Recommanded .class is a property generated by compiler
        										// it return object of java.lang.Class which holds the WishMessage class name not the class or object
        // invoke the bussiness logic
        result=wm.wishMessageGenerator("siddharth");
        System.out.println(result);
        
    }
}
